version: "3"
services:
  api:
    build: .
    ports:
      - "3480:3480"
    environment:
      - REDIS_URL=redis://redis:6379
    env_file:
      - ./.env
    depends_on:
      - mysql_data
    links:
      - redis:redis
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run start

  redis:
    image: "redis:alpine"

  mysql_data:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      max_connections: 1000
    env_file:
      - ./.env
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
  app:
